from fpdf import FPDF

def generate_registration_pdf(data: dict) -> bytes:
    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.add_page()
    pdf.set_fill_color(30, 58, 95)
    pdf.rect(0, 0, 210, 28, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 18)
    pdf.set_xy(0, 8)
    pdf.cell(210, 10, 'Wealixir', align='C')
    pdf.set_font('Helvetica', '', 9)
    pdf.set_xy(0, 18)
    pdf.cell(210, 6, 'Client Registration Summary', align='C')
    pdf.set_text_color(30, 58, 95)
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_xy(20, 36)
    pdf.cell(0, 8, 'Registration Details')
    pdf.set_draw_color(200, 210, 220)
    pdf.set_line_width(0.4)
    pdf.line(20, 46, 190, 46)
    fields = [
        ('Full Name', data.get('name', '-')),
        ('Email Address', data.get('email', '-')),
        ('Mobile Number', data.get('mobile', '-')),
        ('Date of Birth', data.get('dob', '-')),
        ('PAN Number', data.get('pan_number', '-')),
        ('Address', data.get('address') or '-'),
        ('City', data.get('city') or '-'),
        ('Notes', data.get('notes') or '-'),
        ('Submitted At', data.get('submitted_at', '-')),
    ]
    y = 52
    for i, (label, value) in enumerate(fields):
        if i % 2 == 0:
            pdf.set_fill_color(244, 246, 249)
            pdf.rect(20, y, 170, 10, 'F')
        pdf.set_text_color(100, 120, 140)
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_xy(22, y + 2)
        pdf.cell(50, 6, label)
        pdf.set_text_color(30, 40, 55)
        pdf.set_font('Helvetica', '', 9)
        pdf.set_xy(72, y + 2)
        pdf.cell(116, 6, str(value))
        y += 10
    pdf.set_fill_color(244, 246, 249)
    pdf.rect(0, 272, 210, 25, 'F')
    pdf.set_text_color(150, 160, 170)
    pdf.set_font('Helvetica', '', 8)
    pdf.set_xy(0, 279)
    pdf.cell(210, 5, 'This document was auto-generated by the Wealixir Client Portal.', align='C')
    pdf.set_xy(0, 285)
    pdf.cell(210, 5, 'For queries, contact info@wealixir.com', align='C')
    return bytes(pdf.output())
